name: Lint workflow files

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths:
      - .github/workflows/**

permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        shell: bash
        run: |
          bash <(curl -LsS --retry 2 https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
