name: PR Labeler

on:
  pull_request:
    types: [ opened ]

permissions: write-all
jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
