name: Release Drafter

on:
  push:
    branches:
      - master

permissions: write-all
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
